{{- $namespace := .Release.Namespace -}}
{{- range .Values.encryptedSealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .name }}
  namespace: {{ $namespace }}
spec:
  encryptedData: 
  {{- .encryptedData | toYaml | nindent 4 }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .name }}
      namespace: {{ $namespace }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    type: {{ .type | default "Opaque" }}
{{- end }}
