{{ $rel := .Release }}
{{ $fullname := include "eso-secrets.fullname" . }}
{{ if .Values.externalSecretOperator.vaultSecretStore.enabled }}
{{- range .Values.externalSecretOperator.deploySecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $rel.Namespace }}
spec:
  secretStoreRef:
    name: {{ $fullname }}-secret-store
    kind: SecretStore  # or ClusterSecretStore
  refreshPolicy: {{ .refreshPolicy | default "Periodic" }}
  refreshInterval: {{ .refreshInterval | default "1m" }}
  target:
    name: {{ .name }}
    creationPolicy: {{ .creationPolicy | default "Owner" }}
    deletionPolicy: {{ .deletionPolicy | default "Retain" }}
    template:
      type: {{ .type | default "Opaque" }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef: 
        conversionStrategy: {{ .conversionStrategy | default "Default" }}
        decodingStrategy: {{ .decodingStrategy | default "None" }}
        metadataPolicy: {{ .metadataPolicy | default "None" }}
        key: {{ .remoteKey }}
        property: {{ .remoteProperty }}
    {{- end }}
{{- end }}
{{- end }}