{{- if .Values.buckets }}
{{- range .Values.buckets }}
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ceph-rgw-resources.labels" $ | nindent 4 }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .bucketName }}
  bucketName: {{ .bucketName }}
  {{- end }}
  {{- if .generateBucketName }}
  generateBucketName: {{ .generateBucketName }}
  {{- end }}
  storageClassName: {{ $.Values.storageClassName }}
  {{- if .additionalConfig }}
  additionalConfig:
    {{- range $key, $value := .additionalConfig }}
    {{- if or (eq $key "bucketPolicy") (eq $key "bucketLifecycle") }}
    {{ $key }}: {{ $value | quote }}
    {{- else }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
