apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: {{ include "mysql-innodb-cluster.clusterName" . }}
  labels:
    {{- include "mysql-innodb-cluster.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # MySQL Server Configuration
  instances: {{ .Values.mysql.instances }}
  {{- if .Values.mysql.version }}
  version: {{ .Values.mysql.version | quote }}
  {{- end }}
  {{- if .Values.mysql.baseServerId }}
  baseServerId: {{ .Values.mysql.baseServerId }}
  {{- end }}
  
  # MySQL Router Configuration
  {{- with .Values.router }}
  router:
    instances: {{ .instances }}
    {{- if .version }}
    version: {{ .version | quote }}
    {{- end }}
  {{- end }}
  
  # Secret containing root user credentials
  secretName: {{ .Values.secretName }}
  
  # TLS Configuration
  {{- if and .Values.serverCerts .Values.serverCerts.enabled }}
  # Using Vault-issued certificates via cert-manager
  tlsSecretName: {{ .Release.Name }}-mysql-server-cert
  {{- else if .Values.tls.useSelfSigned }}
  # Using self-signed certificates generated by MySQL Operator
  tlsUseSelfSigned: true
  {{- else }}
  # Using custom certificates
  {{- if .Values.tls.tlsSecret }}
  tlsSecretName: {{ .Values.tls.tlsSecret }}
  {{- end }}
  {{- if .Values.tls.tlsCASecret }}
  tlsCASecretName: {{ .Values.tls.tlsCASecret }}
  {{- end }}
  {{- end }}
  
  # Storage Configuration
  datadirVolumeClaimTemplate:
    accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . }}
    {{- end }}
    {{- if .Values.storage.storageClass }}
    storageClassName: {{ .Values.storage.storageClass }}
    {{- end }}
    resources:
      requests:
        storage: {{ .Values.storage.size }}
  
  # Resource Limits and Requests
  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  
  # Custom MySQL Configuration
  {{- if .Values.mycnf }}
  mycnf: {{ .Values.mycnf | quote }}
  {{- end }}
  
  # Service Configuration
  {{- if or .Values.service.annotations .Values.service.labels }}
  serviceAnnotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  
  # Pod Disruption Budget
  {{- if .Values.podDisruptionBudget.enabled }}
  podSpec:
    {{- if .Values.podDisruptionBudget.minAvailable }}
    terminationGracePeriodSeconds: 120
    {{- end }}
  {{- end }}
  
  # Affinity Configuration
  {{- if .Values.affinity.enablePodAntiAffinity }}
  podSpec:
    affinity:
      podAntiAffinity:
        {{- if eq .Values.affinity.podAntiAffinityType "required" }}
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - {{ include "mysql-innodb-cluster.name" . }}
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - {{ .Release.Name }}
          topologyKey: {{ .Values.affinity.topologyKey }}
        {{- else }}
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ include "mysql-innodb-cluster.name" . }}
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: {{ .Values.affinity.topologyKey }}
        {{- end }}
    {{- if .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml .Values.nodeSelector | nindent 6 }}
    {{- end }}
    {{- if .Values.tolerations }}
    tolerations:
      {{- toYaml .Values.tolerations | nindent 6 }}
    {{- end }}
  {{- end }}
  
  # Image Pull Secrets
  {{- if .Values.imagePullSecrets }}
  imagePullSecrets:
  {{- range .Values.imagePullSecrets }}
  - name: {{ .name }}
  {{- end }}
  {{- end }}
  
  # Initialize Database
  {{- if .Values.initDB.enabled }}
  initDB:
    {{- if .Values.initDB.clone }}
    clone:
      {{- toYaml .Values.initDB.clone | nindent 6 }}
    {{- else if .Values.initDB.dump }}
    dump:
      {{- toYaml .Values.initDB.dump | nindent 6 }}
    {{- end }}
  {{- end }}
  
  # Backup Configuration
  {{- if .Values.backup.enabled }}
  {{- if .Values.backup.profiles }}
  backupProfiles:
  {{- range .Values.backup.profiles }}
  - name: {{ .name }}
    {{- if .dumpInstance }}
    dumpInstance:
      {{- if .dumpInstance.dumpOptions }}
      dumpOptions:
        {{- toYaml .dumpInstance.dumpOptions | nindent 8 }}
      {{- end }}
      {{- if .dumpInstance.storage }}
      storage:
        {{- if .dumpInstance.storage.persistentVolumeClaim }}
        persistentVolumeClaim:
          {{- toYaml .dumpInstance.storage.persistentVolumeClaim | nindent 10 }}
        {{- else if .dumpInstance.storage.ociObjectStorage }}
        ociObjectStorage:
          {{- toYaml .dumpInstance.storage.ociObjectStorage | nindent 10 }}
        {{- else if .dumpInstance.storage.s3 }}
        s3:
          {{- toYaml .dumpInstance.storage.s3 | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.backup.schedules }}
  backupSchedules:
  {{- range .Values.backup.schedules }}
  - name: {{ .name }}
    schedule: {{ .schedule | quote }}
    {{- if .backupProfileName }}
    backupProfileName: {{ .backupProfileName }}
    {{- end }}
    enabled: {{ .enabled | default true }}
    {{- if .deleteBackupData }}
    deleteBackupData: {{ .deleteBackupData }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
