---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-concat-ca-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-concat-ca-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-concat-ca-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-concat-ca-sa
roleRef:
  kind: Role
  name: {{ .Release.Name }}-concat-ca-role
  apiGroup: rbac.authorization.k8s.io