{{- $relNamespace := .Release.Namespace -}}
{{- range $i, $serverCert := .Values.dbServerTLSCertIssuers }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serverCert.serviceAccountName | default $serverCert.certName | trim | lower }}
  namespace: {{ $relNamespace }}

---
apiVersion: v1
kind: Secret
metadata:
 name: {{ $serverCert.serviceAccountName | default $serverCert.certName | trim | lower }}-token
 namespace: {{ $relNamespace }}
 annotations:
   kubernetes.io/service-account.name: {{ $serverCert.serviceAccountName | default $serverCert.certName | trim | lower }}
type: kubernetes.io/service-account-token

{{- end }}